MedRegistration/Areas/Reports/Controllers/ReservationLogController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using MedRegistration.Areas.Reports.Models;
using MedRegistration.Controllers;
using MedRegistration.Data;
using MedRegistration.Infrastructure.Authorization;

namespace MedRegistration.Areas.Reports.Controllers
{
    [ReportCheck]
    public class ReservationLogController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            FillViewBag();
            return View(new ReservationLogModel());
        }

        [HttpPost]
        public ActionResult Index(ReservationLogModel model)
        {
            FillViewBag();
            using (var context = new DataContext(lazyLoading: false))
            {
                var query = from l in context.ReservationLogs
                            .Include(x => x.User)
                            .Include(x => x.Doctor)
                            .Include(x => x.Patient)
                    where (!model.UserId.HasValue || l.UserId == model.UserId.Value)
                          && (!model.DoctorId.HasValue || l.DoctorId == model.DoctorId.Value)
                          && (!model.PatientId.HasValue || l.PatientId == model.PatientId.Value)
                          && (!model.FromTime.HasValue || DbFunctions.CreateDateTime(l.Date.Year, l.Date.Month, l.Date.Day, l.FromTime.Hours, l.FromTime.Minutes, l.FromTime.Seconds) >= model.FromTime.Value)
                          && (!model.ToTime.HasValue || DbFunctions.CreateDateTime(l.Date.Year, l.Date.Month, l.Date.Day, l.ToTime.Hours, l.ToTime.Minutes, l.ToTime.Seconds) <= model.ToTime.Value)
                    select l;
                model.Logs = query.ToList();
            }
            return View(model);
        }


        [HttpGet]
        public ActionResult GetPatient(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var patient = context.Patients.Where(p => p.Id == id).Select(p => new { p.Id, p.FirstName, p.LastName }).SingleOrDefault();
                return JsonNet(patient);
            }
        }

        private void FillViewBag()
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                ViewBag.Users = context.Users.AsNoTracking().OrderBy(x => x.FirstName).ThenBy(x => x.LastName).AsEnumerable().Select(u => new User
                {
                    Id = u.Id,
                    FirstName = u.FirstName,
                    LastName = u.LastName
                }).ToList();
                ViewBag.Doctors = context.Doctors.AsNoTracking().OrderBy(x => x.FirstName).ThenBy(x => x.LastName).AsEnumerable().Select(d => new Doctor
                {
                    Id = d.Id,
                    FirstName = d.FirstName,
                    LastName = d.LastName
                }).ToList();
            }
        }
    }
}

MedRegistration/Areas/Reports/Views/ReservationLog/Index.cshtml
@using MedRegistration.Data
@using MedRegistration.Infrastructure
@model MedRegistration.Areas.Reports.Models.ReservationLogModel
@{
    ViewBag.Title = "Лог на резервациите";
}

<form class="form-horizontal" role="form" method="POST" action="@Url.Action("Index", "ReservationLog", new { area = "Reports" })">
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="userSelect" class="col-sm-4 control-label">Потребител:</label>
                    <div class="col-sm-8">
                        <select id="userSelect" class="form-control" name="UserId">
                            <option value="" selected="@(!Model.UserId.HasValue)">Всички</option>
                            @foreach (var user in (List<User>)ViewBag.Users)
                            {
                                <option value="@user.Id" selected="@(Model.UserId.HasValue && Model.UserId.Value == user.Id)">@user.FullName</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="doctorSelect" class="col-sm-4 control-label">Лекар:</label>
                    <div class="col-sm-8">
                        <select id="doctorSelect" class="form-control" name="DoctorId">
                            <option value="" selected="@(!Model.DoctorId.HasValue)">Всички</option>
                            @foreach (var doctor in (List<Doctor>)ViewBag.Doctors)
                            {
                                <option value="@doctor.Id" selected="@(Model.DoctorId.HasValue && Model.DoctorId.Value == doctor.Id)">@doctor.FullName</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="patientSelect" class="col-sm-4 control-label">Пациент:</label>
                    <div class="col-sm-8">
                        <input type="hidden" id="patientSelect" name="PatientId" class="form-control" value="@(Model.PatientId.HasValue ? Convert.ToString(Model.PatientId.Value) : "")" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="fromInput" class="col-sm-4 control-label">Преглед от:</label>
                    <div class="col-sm-8">
                        <input type="datetime-local" id="fromInput" class="form-control" name="FromTime" value="@Model.FromTime.ToUniversalDateTime()" />
                    </div>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="toInput" class="col-sm-4 control-label">Преглед до:</label>
                    <div class="col-sm-8">
                        <input type="datetime-local" id="toInput" class="form-control" name="ToTime" value="@Model.ToTime.ToUniversalDateTime()" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-2 col-xs-push-10">
                <button type="submit" class="btn btn-default btn-block">Покажи</button>
            </div>
        </div>
    </div>
</form>

<div class="container" style="margin-top: 20px">
    @if (Model.Logs != null && Model.Logs.Count > 0)
    {
        <div>
            <table class="table table-bordered table-condensed table-center table-nomen">
                <thead>
                    <tr>
                        <th>Потребител</th>
                        <th>Операция</th>
                        <th>Дата</th>
                        <th>Лекар</th>
                        <th>Пациент</th>
                        <th>Идент. Номер</th>
                        <th>Преглед На</th>
                        <th>Преглед От</th>
                        <th>Преглед До</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var log in Model.Logs)
                    {
                        <tr>
                            <td>
                                @log.User.FullName
                            </td>
                            <td>
                                @if (log.OperationType == OperationType.Create)
                                {
                                    <text>Създаване</text>
                                }
                                else
                                {
                                    <text>Изтриване</text>
                                }
                            </td>
                            <td>
                                @log.LogTime.ToUserDateTime()
                            </td>
                            <td>
                                @log.Doctor.FullName
                            </td>
                            <td>
                                @log.Patient.FullName
                            </td>
                            <td>
                                @log.Patient.IdentNumber
                            </td>
                            <td>
                                @log.Date.ToUserDate()
                            </td>
                            <td>
                                @log.FromTime.ToUserTime()
                            </td>
                            <td>
                                @log.ToTime.ToUserTime()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else if (Model.Logs != null && Model.Logs.Count == 0)
    {
        <h2 style="text-align: center">Няма намерени резултати!</h2>
    }
</div>
@section Scripts
{
    <script src="~/static/js/reports/reservation_log.min.js@("?ver=" + ViewBag.AssemblyVersion)"></script>
}
