MedRegistration/Areas/Common/Controllers/DoctorController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MedRegistration.Controllers;
using MedRegistration.Data;
using MedRegistration.Infrastructure;
using MedRegistration.Infrastructure.Authorization;

namespace MedRegistration.Areas.Common.Controllers
{
    public class DoctorController : BaseController
    {
        private static readonly object locker = new object();
        [HttpGet]
        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetDoctors()
        {
            using (var context = new DataContext())
            {
                var doctors = from d in context.Doctors.Include(x => x.Title)
                              select new
                              {
                                  d.Id,
                                  Title = d.Title.Description,
                                  d.PhoneNumber,
                                  d.FirstName,
                                  d.LastName
                              };
                return JsonNet(doctors.ToList());
            }
        }

        [HttpGet]
        public ActionResult GetDoctor(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var doctors = from d in context.Doctors
                                               .Include(x => x.Title)
                                               .Include(x => x.Specialities)
                              where d.Id == id
                              select d;
                return JsonNet(doctors.SingleOrDefault());
            }
        }

        [HttpGet]
        public ActionResult CanBeDeleted(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var hasReservations = context.Doctors.Where(p => p.Id == id).SelectMany(d => d.Reservations).Any();
                return JsonNet(HttpContext.User.IsAdmin() && !hasReservations);
            }
        }

        [HttpGet]
        public ActionResult Add()
        {
            return PartialView();
        }

        [HttpPost]
        [AntiForgeryValidate]
        public ActionResult Save(Doctor doctor, Speciality[] specialities)
        {
            try
            {
                using (var context = new DataContext())
                {
                    if (doctor.Id == 0)
                    {
                        context.Doctors.Add(doctor);
                    }
                    else
                    {
                        var dbDoctor = context.Doctors.SingleOrDefault(d => d.Id == doctor.Id);
                        if (dbDoctor == null)
                            return CreateResult(ResultType.Deleted);
                        dbDoctor.TitleId = doctor.TitleId;
                        dbDoctor.FirstName = doctor.FirstName;
                        dbDoctor.LastName = doctor.LastName;
                        dbDoctor.PhoneNumber = doctor.PhoneNumber;
                        dbDoctor.DefaultExamTime = doctor.DefaultExamTime;

                        dbDoctor.Specialities.Clear();
                    }
                    context.SaveChanges();

                    var specialityDoctor = context.Doctors.Single(d => d.Id == doctor.Id);
                    if (specialities != null)
                    {
                        foreach (var speciality in specialities)
                        {
                            var spec = context.Specialities.Single(s => s.Id == speciality.Id);
                            specialityDoctor.Specialities.Add(spec);
                        }
                    }

                    context.SaveChanges();
                }
                return CreateResult(ResultType.Success);
            }
            catch
            {
                return CreateResult(ResultType.Fail);
            }
        }

        [HttpPost]
        [AntiForgeryValidate]
        public ActionResult Delete(int id)
        {
            lock (locker)
            {
                try
                {
                    using (var context = new DataContext())
                    {
                        var doctor = context.Doctors.SingleOrDefault(p => p.Id == id);
                        if (doctor != null)
                            context.Doctors.Remove(doctor);
                        context.SaveChanges();
                    }
                    return CreateResult(ResultType.Success);

                }
                catch (Exception)
                {
                    return CreateResult(ResultType.Fail);
                }
            }
        }
    }
}

MedRegistration/Areas/Common/Controllers/PatientController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MedRegistration.Controllers;
using MedRegistration.Data;
using MedRegistration.Infrastructure;

namespace MedRegistration.Areas.Common.Controllers
{
    public class PatientController : BaseController
    {
        private static readonly object locker = new object();
        [HttpGet]
        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPatients()
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var patients = from p in context.Patients
                                                .Include(x => x.PatientPhones)
                               let primaryPhone = p.PatientPhones.FirstOrDefault(pp => pp.IsPrimary)
                               orderby p.Reservations.Count() descending
                               select new
                               {
                                   p.Id,
                                   fn = p.FirstName,
                                   ln = p.LastName,
                                   @in = p.IdentNumber,
                                   pn = primaryPhone.Number,
                                   em = p.Email
                               };
                return JsonNet(patients.ToList());
            }
        }

        [HttpGet]
        public ActionResult GetPatient(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var dbPatient = context.Patients
                                       .Where(p => p.Id == id)
                                       .Include(x => x.PatientPhones)
                                       .Include(x => x.PatientFundInfo)
                                       .SingleOrDefault();
                return JsonNet(dbPatient);
            }
        }

        [HttpGet]
        public ActionResult CanBeDeleted(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var hasReservations = context.Patients.Where(p => p.Id == id).SelectMany(d => d.Reservations).Any();
                return JsonNet(!hasReservations);
            }
        }

        [HttpGet]
        public ActionResult GetPatientFundInfo(int id)
        {
            using (var context = new DataContext(lazyLoading: false))
            {
                var patient = context.Patients.Where(p => p.Id == id).Include(p => p.PatientFundInfo).Single();
                return JsonNet(patient.PatientFundInfo);
            }
        }

        [HttpGet]
        public ActionResult Add()
        {
            return PartialView();
        }

        [HttpPost]
        [AntiForgeryValidate]
        public ActionResult Save(Patient patient)
        {
            try
            {
                using (var context = new DataContext())
                {
                    if (patient.Id == 0)
                    {
                        context.Patients.Add(patient);
                    }
                    else
                    {
                        var dbPatient = context.Patients
                                               .Where(p => p.Id == patient.Id)
                                               .Include(x => x.PatientPhones)
                                               .Include(x => x.PatientFundInfo)
                                               .SingleOrDefault();
                        if (dbPatient == null)
                            return CreateResult(ResultType.Deleted);
                        dbPatient.FirstName = patient.FirstName;
                        dbPatient.MiddleName = patient.MiddleName;
                        dbPatient.LastName = patient.LastName;
                        dbPatient.IdentNumberTypeId = patient.IdentNumberTypeId;
                        dbPatient.IdentNumber = patient.IdentNumber;
                        dbPatient.GenderId = patient.GenderId;
                        dbPatient.Email = patient.Email;
                        dbPatient.Address = patient.Address;
                        dbPatient.Town = patient.Town;
                        dbPatient.PostCode = patient.PostCode;
                        dbPatient.Note = patient.Note;
                        context.PatientPhones.RemoveRange(dbPatient.PatientPhones);
                        foreach (var phone in patient.PatientPhones)
                        {
                            dbPatient.PatientPhones.Add(phone);
                        }

                        if (patient.PatientFundInfo != null)
                        {
                            if (dbPatient.PatientFundInfo == null)
                                dbPatient.PatientFundInfo = new PatientFundInfo();
                            dbPatient.PatientFundInfo.FundId = patient.PatientFundInfo.FundId;
                            dbPatient.PatientFundInfo.FundCardNumber = patient.PatientFundInfo.FundCardNumber;
                            dbPatient.PatientFundInfo.FundCardExpiration = patient.PatientFundInfo.FundCardExpiration;
                        }
                        else
                        {
                            if (dbPatient.PatientFundInfo != null)
                                context.PatientFundInfoes.Remove(dbPatient.PatientFundInfo);
                        }
                    }
                    context.SaveChanges();
                }
                return CreateResult(ResultType.Success);
            }
            catch (Exception)
            {
                return CreateResult(ResultType.Fail);
            }
        }

        [HttpPost]
        [AntiForgeryValidate]
        public ActionResult Delete(int id)
        {
            lock (locker)
            {
                try
                {

                    using (var context = new DataContext())
                    {
                        var patient = context.Patients.SingleOrDefault(p => p.Id == id);
                        if (patient != null)
                        {
                            context.Patients.Remove(patient);
                            context.SaveChanges();
                        }
                    }
                    return CreateResult(ResultType.Success);
                }
                catch (Exception)
                {
                    return CreateResult(ResultType.Fail);
                }
            }
        }
    }
}

MedRegistration/Areas/Configuration/Controllers/FundController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MedRegistration.Controllers;
using MedRegistration.Data;
using MedRegistration.Infrastructure.Authorization;

namespace MedRegistration.Areas.Configuration.Controllers
{
    [AdminCheck]
    public class FundController : BaseController
    {
        private static readonly object locker = new object();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Fund fund)
        {
            try
            {
                using (var context = new DataContext())
                {
                    if (fund.Id == 0)
                    {
                        context.Funds.Add(fund);
                    }
                    else
                    {
                        var dbFund = context.Funds.SingleOrDefault(f => f.Id == fund.Id);
                        if (dbFund == null)
                            return CreateResult(ResultType.Deleted);
                        dbFund.Name = fund.Name;
                    }
                    context.SaveChanges();
                    return CreateResult(ResultType.Success);
                }
            }
            catch (Exception)
            {
                return CreateResult(ResultType.Fail);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            lock (locker)
            {
                try
                {
                    using (var context = new DataContext())
                    {

                        var dbFund = context.Funds.SingleOrDefault(f => f.Id == id);
                        if (dbFund == null)
                            return CreateResult(ResultType.Deleted);

                        if (dbFund.PatientFundInfoes.Any() || dbFund.PaymentInfoes.Any())
                            return CreateResult(ResultType.Fail, "Този фонд се използва и неможе да бъде изтрит!");
                        context.Funds.Remove(dbFund);
                        context.SaveChanges();
                        return CreateResult(ResultType.Success);
                    }
                }
                catch
                {
                    return CreateResult(ResultType.Fail);
                }
            }
        }
    }
}

MedRegistration/Areas/Configuration/Controllers/MessagesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MedRegistration.Controllers;
using MedRegistration.Data;
using MedRegistration.Infrastructure.Authorization;

namespace MedRegistration.Areas.Configuration.Controllers
{
    [MessageCheck]
    public class MessagesController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Send(Message message)
        {
            try
            {
                using (var context = new DataContext())
                {
                    message.UserId = HttpContext.User.UserId();
                    context.Messages.Add(message);
                    context.SaveChanges();
                    return CreateResult(ResultType.Success);
                }
            }
            catch (Exception ex)
            {
                return CreateResult(ResultType.Fail, ex.Message);
            }
        }

        [HttpGet]
        public ActionResult GetMessages()
        {
            try
            {
                using (var context = new DataContext(lazyLoading: false))
                {
                    var userId = HttpContext.User.UserId();
                    var messages = from m in context.Messages
                                   where m.UserId == userId
                                   orderby m.SendAt descending
                                   select new
                                   {
                                       m.Text,
                                       m.SendAt,
                                       Type = (int)m.Type,
                                       Validity = (int)m.Validity,
                                       m.ValidFrom,
                                       m.ValidTo,
                                       Recipients = from r in m.Recipients
                                                    select new
                                                    {
                                                        r.Recipient.Id,
                                                        r.Recipient.FirstName,
                                                        r.Recipient.LastName,
                                                        r.ReadAt
                                                    }
                                   };
                    return JsonNet(messages.ToList());
                }
            }
            catch (Exception ex)
            {
                return CreateResult(ResultType.Fail, ex.Message);
            }
        }
    }
}

MedRegistration/Views/Shared/Language.cshtml
@using MedRegistration.Infrastructure
<div class="language">
    <ul>
        @foreach (var lang in Translation.Languages)
        {
            <li class="flag flag-@lang.Key" data-title="@lang.Value" ng-click="translation.setLanguage('@lang.Key')" />
        }
    </ul>
</div>

MedRegistration/Views/Shared/Main.cshtml
@using System.Web
@using MedRegistration.Infrastructure.Authorization
<!DOCTYPE html>
<html ng-app="app">
<head>
    <title>@RenderSection("Title", false)</title>
    <meta charset="utf-8" />
    <meta name="author" content="Ventsislav Mladenov">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.css" />

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/select2/3.4.8/select2.css" />
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/select2/3.4.8/select2-bootstrap.css" />

    <link href="~/static/css/main.min.css@("?ver=" + ViewBag.AssemblyVersion)" rel="stylesheet">
    <link href="~/static/css/menu.min.css@("?ver=" + ViewBag.AssemblyVersion)" rel="stylesheet">
    <link href="~/static/css/language.min.css@("?ver=" + ViewBag.AssemblyVersion)" rel="stylesheet" />
    @RenderSection("Styles", false)
</head>
<body ng-controller="rootController" ng-init="init(@HttpContext.Current.User.UserId())" ng-cloak>
    @Html.Partial("Language")
    @Html.Partial("Menu")

    <script src="//cdn.jsdelivr.net/modernizr/2.8.2/modernizr.min.js" type="text/javascript"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js" type="text/javascript"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js" type="text/javascript"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular-cookies.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.min.js" type="text/javascript"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js" type="text/javascript"></script>
    <script src="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.js" type="text/javascript"></script>
    <script src="//cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.min.js" type="text/javascript"></script>
    <script src="//cdn.jsdelivr.net/select2/3.4.8/select2.min.js" type="text/javascript"></script>
    <script src="//cdn.jsdelivr.net/select2/3.4.8/select2_locale_bg.js" type="text/javascript"></script>

    <script src="~/Scripts/jquery.signalR-2.1.1.min.js" type="text/javascript"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>

    @RenderBody()

    <script src="~/static/js/slider.min.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    <script src="~/static/js/functions.min.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    <script src="~/static/js/ui-med.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    <script src="~/static/js/common-cntrl.min.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    <script src="~/static/js/i18n/@(ViewBag.Lang).js" type="text/javascript"></script>
    <script src="~/static/js/translation.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    <script src="~/static/js/app.min.js@("?ver=" + ViewBag.AssemblyVersion)" type="text/javascript"></script>
    @RenderSection("Scripts", false)
</body>
</html>

MedRegistration/Views/Shared/Menu.cshtml
@using System.Web
@using MedRegistration.Infrastructure.Authorization
<nav class="menu-container">
    @if (Request.IsAuthenticated)
    {
        <div class="user-name">
            <span>{{translation.texts.welcome}}: @HttpContext.Current.User.FullName()</span>
            <a href="@Url.Action("Logout", "Account", new { area = "" })" class="clear-href" ng-bind="translation.texts.logout">Log out</a>
        </div>
    }
    <div class="menu">
        <ul>
            <li>
                <a href='@Url.Action("Index", "Home", new { area = "" })'>
                    <span ng-bind="translation.texts.home">Home</span>
                </a>
            </li>
            <li class='has-sub'>
                <a href='#'>
                    <span ng-bind="translation.texts.nomenclature">Nomenclature</span>
                </a>
                <ul>
                    <li>
                        <a href='@Url.Action("List", "Doctor", new { area = "Common" })'>
                            <span ng-bind="translation.texts.doctors">Doctors</span>
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("List", "Patient", new { area = "Common" })'>
                            <span ng-bind="translation.texts.patients">Patients</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href='@Url.Action("Index", "Reservation", new { area = "Reservation" })'>
                    <span ng-bind="translation.texts.schedule">Schedule</span>
                </a>
            </li>
            <li class='has-sub @ViewBag.ReportViewClass'>
                <a href='#'>
                    <span ng-bind="translation.texts.reports">Reports</span>
                </a>
                <ul>
                    <li>
                        <a href='@Url.Action("Index", "ReservationLog", new { area = "Reports" })'>
                            <span ng-bind="translation.texts.reservationLog">Reservation log</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class='has-sub'>
                <a href='#'>
                    <span ng-bind="translation.texts.configuration">Configuration</span>
                </a>
                <ul>
                    <li class="@ViewBag.AdminViewClass">
                        <a href='@Url.Action("Index", "UserAdministration", new { area = "Configuration" })'>
                            <span ng-bind="translation.texts.users">Users</span>
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Edit", "UserAdministration", new { area = "Configuration" })'>
                            <span ng-bind="translation.texts.changePersonalInfo">Change personal info</span>
                        </a>
                    </li>
                    <li class="has-sub @ViewBag.AdminViewClass">
                        <a href="#">
                            <span ng-bind="translation.texts.nomenclature">Nomenclature</span>
                        </a>
                        <ul>
                            <li>
                                <a href='@Url.Action("Index", "Speciality", new { area = "Configuration" })'>
                                    <span ng-bind="translation.texts.specialties">Specialties</span>
                                </a>
                            </li>
                            <li>
                                <a href='@Url.Action("Index", "Fund", new { area = "Configuration" })'>
                                    <span ng-bind="translation.texts.funds">Funds</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="@ViewBag.MessageViewClass">
                        <a href='@Url.Action("Index", "Messages", new { area = "Configuration" })'>
                            <span ng-bind="translation.texts.messages">Messages</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>